import math


# BOOLEAN BODY ATTRIBUTES
ARMS 			= 1
ROTATING_HIP 		= 1

# QUANTITATIVE BODY ATTRIBUTES
FOOT_HEIGHT     = 0.33
SHIN_HEIGHT     = 2.5
THIGH_HEIGHT    = 2
TORSO_HEIGHT    = 3
NECK_HEIGHT     = 0.33
HEAD_HEIGHT     = 0.65
SHOULDER_HEIGHT = 0.4
ARM_HEIGHT      = 1.75

TORSO_WIDTH     = 2
SHOULDER_WIDTH  = 0.2
ARM_WIDTH       = 0.5

FOOT_LENGTH     = 1.25
TORSO_DEPTH     = 1.2

ITERATIONS      	 	= 1000
