import math


# BOOLEAN BODY ATTRIBUTES
ARMS 			= 1
ROTATING_HIP 	= 1

# QUANTITATIVE BODY ATTRIBUTES
FOOT_HEIGHT     = 0.33
SHIN_HEIGHT     = 2.5
THIGH_HEIGHT    = 2
TORSO_HEIGHT    = 3
NECK_HEIGHT     = 0.33
HEAD_HEIGHT     = 0.65
SHOULDER_HEIGHT = 0.4
ARM_HEIGHT      = 1.75

TORSO_WIDTH     = 2
SHOULDER_WIDTH  = 0.2
ARM_WIDTH       = 0.5

FOOT_LENGTH     = 1.25
TORSO_DEPTH     = 1.2

# ITERATIONS      	 	= 1000
# MOTOR_STRENGTH  	 	= 30

# AMPLITUDE_BACK_LEG 	 	= math.pi/4
# FREQUENCY_BACK_LEG 	 	= 8
# PHASE_OFFSET_BACK_LEG  	= 5

# AMPLITUDE_FRONT_LEG 	= math.pi/4
# FREQUENCY_FRONT_LEG 	= 8
# PHASE_OFFSET_FRONT_LEG 	= 5

# NUM_SENSOR_NEURONS 		= 9
# NUM_MOTOR_NEURONS 		= 8
# SENSOR_VALUES 			= "data/sensor_values.npy"
# MOTOR_VALUES 			= "data/motor_values.npy"
# MOTOR_JOINT_RANGE		= 0.2

# NUMBER_OF_GENERATIONS	= 10
# POPULATION_SIZE			= 1